@number =201
POST {{api_url}}/api/projects/{{number}}/update/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json
X-HOST: http://lviv.pb.org.ua
access-token: {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images[]"; filename="image.png"

< ./../../src/DataFixtures/data/images/1be51092-75bf-455f-b0f4-cf16ec629bf6.png
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="budget"

198000.99
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="name"

Project UPDATED
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="short"

my short description
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="description"

description can contain <b>HTML</b>
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

education
--WebAppBoundary--

###POST {{api_url}}/api/projects/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json
X-HOST: http://lviv.pb.org.ua
access-token: {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images[]"; filename="image.png"

< ./../../src/DataFixtures/data/images/1be51092-75bf-455f-b0f4-cf16ec629bf6.png
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="budget"

198000.99
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="name"

Project to feature!!!
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="short"

my short description
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="description"

description can contain <b>HTML</b>
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

education
--WebAppBoundary--

###
GET http://localhost:8081/api/projects/3/
Accept: application/json
X-HOST: http://lviv.pb.org.ua

###
POST http://localhost:8081/api/projects/find/
Content-Type: application/json
Accept: application/json
X-HOST: http://lviv.pb.org.ua

{
  "result": {
    "limit": 50,
    "offset": 0
  }
}

###

