POST {{api_url}}/api/projects/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json
X-HOST: http://lviv.pb.org.ua
access-token: {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images[]"; filename="image.png"

< ./../../src/DataFixtures/data/images/1be51092-75bf-455f-b0f4-cf16ec629bf6.png
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="budget"

198000.99
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="name"

Project to virtualization
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="short"

my short description
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="description"

Docker is an open platform for developing, shipping, and running applications. Docker enables you to separate your applications from your infrastructure so you can deliver software quickly. With Docker, you can manage your infrastructure in the same ways you manage your applications. By taking advantage of Docker's methodologies for shipping, testing, and deploying code, you can significantly reduce the delay between writing code and running it in production.
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

education
--WebAppBoundary--

###
@number = 12

POST {{api_url}}/api/projects/{{number}}/update/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Accept: application/json
X-HOST: http://lviv.pb.org.ua
access-token: {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="images[]"; filename="image.png"

< ./../../src/DataFixtures/data/images/cbeb527f-ed49-4f3d-9888-a173a3cb8674.png
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="images[]"; filename="image.png"

< ./../../src/DataFixtures/data/images/155bcca4-d7c0-4e00-80ef-470913b248f4.png
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="budget"

198000.99
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="name"

Project UPDATED
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="short"

my short description
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="description"

description can contain <b>HTML</b>
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="category"

education
--WebAppBoundary--

###
GET http://localhost:8081/api/projects/12/
Accept: application/json
X-HOST: http://lviv.pb.org.ua

###
POST http://localhost:8081/api/projects/find/
Content-Type: application/json
Accept: application/json
X-HOST: http://lviv.pb.org.ua

{
  "search": "open platform for",
  "result": {
    "limit": 10,
    "offset": 0
  }
}

###

