POST {{api_url}}/api/user/registration/request/
Content-Type: application/json
Accept: application/json

{
  "name": "Test",
  "surname": "Surname",
  "patronymic": "Test",
  "email": "app5.test@mail.com",
  "birthday": "1999-05-30",
  "password": "password",
  "re_password": "password"
}

###

GET {{api_url}}/api/user/registration/confirm/{{confirm_token}}
Accept: application/json

###

POST http://localhost:8081/api/user/login/
Content-Type: application/json
Accept: application/json

{
  "email": "app5.test@mail.com",
  "password": "password"
}

###

GET http://localhost:8081/api/user/
Accept: application/json
access-token: {{access_token}}

###