version: '3'
services:
  frontend-nodejs:
    image: node:18.16
    volumes:
      - ./frontend-react:/var/www/frontend-react
    working_dir: /var/www/frontend-react
    tty: true

  frontend-nginx:
    build:
      context: ./frontend-react/docker
      dockerfile: nginx.docker
    volumes:
      - ./frontend-react:/var/www/frontend-react
    depends_on:
      - api-php-fpm
    ports:
      - "5555:80"

  api-nginx:
    build:
      context: './api/docker'
      dockerfile: 'nginx.dockerfile'
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: './api/docker'
      dockerfile: 'php-fpm.dockerfile'
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    restart: on-failure
    user: root
    depends_on:
      - api-mysql
      - mailer
      - storage

  api-php-cli:
    build:
      context: './api/docker'
      dockerfile: 'php-cli.dockerfile'
    volumes:
      - ./api:/var/www/api
    command: >
      sh -c "
      composer install --no-interaction --no-cache
      && php bin/console doctrine:database:create --if-not-exists
      && php bin/console doctrine:migrations:migrate --all-or-nothing --allow-no-migration -vvv
      && crond -f"
    working_dir: /var/www/api
    restart: on-failure
    user: root
    depends_on:
      - api-mysql
      - mailer
      - storage

  api-mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  storage:
    build:
      context: ./storage/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./storage:/app
    ports:
      - "8083:80"
  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app

  mailer:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8082:8025"

volumes:
  mysql_data: