version: '3'
services:
  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: nginx.docker
    volumes:
      - ./frontend:/var/www/frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
  frontend-nodejs:
    image: node:18.16
    volumes:
      - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true

  api-nginx:
    build:
      context: './api/docker'
      dockerfile: 'nginx.dockerfile'
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: './api/docker'
      dockerfile: 'php-fpm.dockerfile'
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    restart: on-failure
    user: root
    command: >
      sh -c "
      composer install --no-interaction --no-cache
      && php bin/console doctrine:database:create --if-not-exists
      && php bin/console doctrine:migrations:migrate --all-or-nothing --allow-no-migration -vvv
      && docker-php-entrypoint php-fpm"
    environment:
      PHP_IDE_CONFIG: serverName=app-backend
    depends_on:
      - api-mysql
      - mailer
  api-mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailer:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8082:8025"

volumes:
  mysql_data: