version: '3'
services:
  api-nginx:
    build:
      context: './api/docker'
      dockerfile: 'nginx.dockerfile'
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm
    networks:
      - mynetwork

  api-php-fpm:
    build:
      context: './api/docker'
      dockerfile: 'php-fpm.dockerfile'
    volumes:
      - ./api:/var/www/api
    restart: on-failure
    user: root
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - api-mysql
      - mailer
      - storage
    networks:
      - mynetwork

  api-php-cli:
    build:
      context: './api/docker'
      dockerfile: 'php-cli.dockerfile'
    volumes:
      - ./api:/var/www/api
    restart: on-failure
    user: root
    depends_on:
      - api-mysql
      - mailer
      - storage
    networks:
      - mynetwork

  api-mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  storage:
    build:
      context: ./storage/docker
    volumes:
      - ./storage:/app
    ports:
      - "8083:80"

  storage-ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app
    platform: linux/amd64
    networks:
      - mynetwork

  mailer:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8082:8025"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge